# Site settings
title: Umutoni Chantal
url: "https://Chantal1umutoni.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: chantal.umutoni@aims.ac.rw
author: Umutoni Chantal
avatar: "https://github.com/Chantal1umutoni/Chantal1umutoni.github.io/blob/gh-pages/UMUTONI Chantal-MSc in Mathematical Sciences-AIMS.jpg?raw=true"
profile: Know what you have and use what you know. 
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:chantal.umutoni@aims.ac.rw"
  GitHub: "https://Chantal1umutoni.github.io"
  Linkedin: "https://www.linkedin.com/in/chantal-umutoni-a8b107161"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    #Category: /category/
    #Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
